### ISSUE TITLE
Uncaught TypeError: pkceChallenge.default is not a function

### ISSUE THREAD

**Issue by timeisgolden** [crouchcd/pkce-challenge#13]
Hello, Support Team, I am trying to generate code_verifier and code_challenge by using this module.
but I am getting the following error.
![image](https://user-images.githubusercontent.com/54345950/156228184-279e29ee-be07-40d6-bc6b-e836b1af2692.png)

Below is the code that I tried.
```
import * as pkceChallenge from 'pkce-challenge';
pkceChallenge.default(128)
```
can you help me?

**Comment by crouchcd** [comment]
How does it work if you do the following instead?
```
import pkceChallenge from 'pkce-challenge'
pkceChallenge(128)
```
I am unable to reproduce. Using `node@14.9.0`, `create-react-app@5`,  `create-react-app --template typescript`, `pkce-challenge@2.2.0`. What versions are you using? How is it compiled for use in the browser?

**Comment by devmanateam** [comment]
```
import pkceChallenge from 'pkce-challenge'
pkceChallenge(128)
```
If I use this code, I am getting like this.
![image](https://user-images.githubusercontent.com/54345950/156242412-d857bd76-400e-4f9a-8afa-bfd1ac0ae1d5.png)

I used this version
pkce-challenge@2.2.0
and I have created my project using `npm create vite@latest my-react-app --template react-ts`

**Comment by crouchcd** [comment]
Okay so this is an issue with how vite + rollup includes native Node modules. I used the same react-ts template as you and here's what I had to do to get things to play nicely with native modules in the browser.

```ts
// ./vite.config.ts
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      // npm install crypto-browserify
      crypto: "crypto-browserify",
      // npm install readable-stream
      stream: "readable-stream",
      // npm install events
      events: "events",
      // npm install buffer
      buffer: "buffer",
    },
  },
});
```

```html
<!-- ./index.html -->
<!-- added this to <head> -->
<script>
  window.global = window;
</script>
```

Set `"esModuleInterop": true` in ./tsconfig.json.

And then I was able to use `pkce-challenge`:
```ts
// ./src/App.tsx
import * as pkceChallenge from 'pkce-challenge'
const challengePair = pkceChallenge(128)
console.log('verified:', pkceChallenge.verifyChallenge(challengePair.code_verifier, challengePair.code_challenge))
```

Hope this helps!

**Comment by crouchcd** [comment]
@timeisgolden Please take a look at release [3.0.0](https://github.com/crouchcd/pkce-challenge/releases/tag/3.0.0). It takes care of the default browser polyfills or uses native crypto if running in Node (all handled by crypto-js). You shouldn't have to do any of the steps I mentioned above with this update. Sorry for the hassle if you did go that route ^.
