### ISSUE TITLE
The default import is not a function but an object includes exported functions

### ISSUE THREAD

**Issue by saschanaz** [crouchcd/pkce-challenge#18]
It seems package.json does not include "type": "module", so Node.js just imports the CommonJS version. Thus the default export becomes the module object instead of the function.

```
> node
Welcome to Node.js v19.8.1.
Type ".help" for more information.
> (await import('pkce-challenge')).default
{
  generateChallenge: [Getter],
  default: [Getter],
  verifyChallenge: [Getter]
}
```

Perhaps you need to add conditional imports? https://nodejs.org/api/packages.html#conditional-exports

**Comment by crouchcd** [comment]
closed by #20
