### ISSUE TITLE
Use Web Crypto API?

### ISSUE THREAD

**Issue by saschanaz** [crouchcd/pkce-challenge#19]
Node.js added Web Crypto API support [since version 15](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto#browser_compatibility), and marked it stable [as of version 19](https://nodejs.org/api/webcrypto.html). It seems reasonable to consider using it instead of crypto.js, what do you think?

(Using it in 16 and 18 does not warn as of 16.20.0 and 18.15.0)

**Comment by crouchcd** [comment]
@saschanaz I agree. The current layout is,
- version 2: Node.js only (Web support with https://www.npmjs.com/package/crypto-browserify)
- version 3: Node.js and JavaScript support with crypto-js which determines what crypto to use at runtime. (See https://github.com/brix/crypto-js/blob/7c26cc72a618053c294309c22c95a895af39b7b7/core.js#L51-L55)
- Propose version 4 which would use native Web APIs that are now supported in LTS Node.js versions starting with 16.20.0

Let me know if this is one that you would like to work on.

**Comment by saschanaz** [comment]
I can work on it this weekend 👍
