### ISSUE TITLE
pkceChallenge is not a function

### ISSUE THREAD

**Issue by andrewlorenz** [crouchcd/pkce-challenge#21]
```
import pkceChallenge from 'pkce-challenge';
...
const pkce = pkceChallenge();

TypeError: pkceChallenge is not a function
```
And indeed its not! 
```
import pkceChallenge from 'pkce-challenge';
console.log('pkceChallenge', pkceChallenge);

pkceChallenge {
  generateChallenge: [Getter],
  default: [Getter],
  verifyChallenge: [Getter]
}
```
so for now I'm getting round it by doing
```
const pkce = pkceChallenge.default();
```

**Comment by hjdhjd** [comment]
I can confirm this issue - it began in 3.0.0 apparently. reverting down to 2.2.0 solves the issue.

**Comment by saschanaz** [comment]
(See also #18)

**Comment by crouchcd** [comment]
@andrewlorenz and others, Yes this is related to #18 and how parcel.js separates commonjs/esmodules. I was under the impression that bundlers would get this right on their own. See https://parceljs.org/getting-started/library/#commonjs-and-es-modules.
> "Tools that consume your library will choose whichever of these they support."

It was my fault that I did not test both commonjs and esmodules thoroughly.

Can you do me a favor and see if this PR fixes it for you #22 . If so, I will merge and bump the major version. The reason being that is those who have gotten around the issue will be impacted by the fix.

**Comment by saschanaz** [comment]
You need to publish a prerelease for others to test it. I tried building it myself but parcel never works on my machine. I'd rather drop CJS support at this point.

**Comment by saschanaz** [comment]
Now that you merged #20, can you publish a new release so that we can test it? 🙏

**Comment by crouchcd** [comment]
@saschanaz Done! Sorry for the delay! Please see https://www.npmjs.com/package/pkce-challenge/v/4.0.1

**Comment by saschanaz** [comment]
Works great, thanks!
