### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by dugdug36** [crouchcd/pkce-challenge#27]
Hello, 
I found 2 security weakness in your dependencies : 
https://github.com/advisories/GHSA-grv7-fg5c-xmjg
https://github.com/advisories/GHSA-952p-6rrq-rcjv
Can you fix it ?

Best regards

**Comment by crouchcd** [comment]
@dugdug36 Both vulnerabilities are taken care of: fc813b74a10edd9052af2ea787b1e1f237fd41c6. Thanks.
