### ISSUE TITLE
It looks like TypeScript definition is not correct

### ISSUE THREAD

**Issue by rstefko** [crouchcd/pkce-challenge#3]
If I use

`import pkceChallenge from 'pkce-challenge';`

then

`const challenge = pkceChallenge(128);`

generates runtime error, because pkceChallenge is undefined.

**Comment by crouchcd** [comment]
Can you share what the compile output looks like and/or what instructions you use to compile? I haven't been able to reproduce while trying with a variety of settings.

**Comment by crouchcd** [comment]
@rstefko Can you provide more detail?

**Comment by crouchcd** [comment]
Closing until further notice.

**Comment by meck93** [comment]
@crouchcd To provide a little bit more context. I had a similar issue. 
The following code only worked once I enabled `esModuleInterop: true` in the `tsconfig.json`. 

```typescript
import * as pkceChallenge from "pkce-challenge";
```

**Comment by crouchcd** [comment]
@meck93 Okay thanks for sharing. Yes, good idea to update the README with this information. BTW I had to explicitly use `default` with import star. I guess that's because, like the docs say, ES6 specs require an object for a namespace import. If that's okay, would you like to update README?

```js
import * as pkceChallenge from "pkce-challenge";

pkceChallenge.default();
```
