### ISSUE TITLE
crypto: deprecated Package

### ISSUE THREAD

**Issue by distancerunner** [crouchcd/pkce-challenge#9]
This package is deprecated:
https://www.npmjs.com/package/crypto

I have no clue how to replace it. crypto-js is not working.

**Comment by crouchcd** [comment]
@distancerunner For a browser environment, please see this example [using pkce-challenge in the browser](https://glitch.com/edit/#!/crypto-in-browser) which polyfills the built-in Node.js crypto module. Let me know if you any questions/issues with that approach.

**Comment by distancerunner** [comment]
It was difficult to get it working in an Angular 10 project.

I tried to use crypto-browserify and got other problems. It was not compiling with npm and there was missing global, process and another variable. So I added many ideas to polyfills, from some sources, to the project, and it was compiling. But than in the browser it was not running. It was a very strange behavior, which I never had before.

So I rolled back all changes and started from beginning again. 

I replaced 
    `const randomIndices = randomBytes(size);`
 with
    `const array = new Uint8Array(128);
    const randomIndices = window.crypto.getRandomValues(array);`

and used crypto-js and modified "generateChallenge"
`generateChallenge(codeVerifier): any {
    const hash = cryptojs.SHA256(codeVerifier).toString(cryptojs.enc.Base64);

    return this.base64UrlEncode(hash);
  }`

Now it is working.

**Comment by crouchcd** [comment]
I'm glad you found a solution. If you are happy with it, then I can close the issue.

I tried reproducing in Angular 10 and saw the issues you described with missing dependencies. I was able to get a working version if you want to try again:
`npm install buffer crypto-browserify process stream-browserify`

**polyfills.ts**
```
...
import { Buffer } from 'buffer';
import * as process from 'process';
(window as any).process = process;
(window as any).Buffer = Buffer;
...
```

**angular.json**
`architect.build.options.allowedCommonJsDependencies = ["pkce-challenge"]`

**tsconfig.json**
`compilerOptions.paths.crypto = ["./node_modules/crypto-browserify"]`
`compilerOptions.paths.stream = ["./node_modules/stream-browserify"]`

**index.html**
```
...
<script>var global = global || window;</script>
...
```

**Comment by distancerunner** [comment]
This look like a good solution. Yes, you can close it.

Thanks for your effort.

**Comment by crouchcd** [comment]
@GabeDahl I don't have a plan formulated yet, but there is a need. I intend to investigate more this weekend. Feel free to open a new issue to track the progress on this.

**Comment by crouchcd** [comment]
@GabeDahl Please see [my comment on #13](https://github.com/crouchcd/pkce-challenge/issues/13#issuecomment-1081379606) for a resolution to the scaffolding hassle.
